version: "3"

networks:
  my-net:
    driver: bridge

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_server
    ports:
      - 80:3000
    networks:
      - my-net

  socket:
    build:
      context: ./socket/
      dockerfile: Dockerfile
    container_name: socket_server
    ports:
      - 3001:3001
    networks:
      - my-net

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - my-net

  worker:
    build:
      context: ./bunWorker/
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    networks:
      - my-net

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./backend/dbBackup/leetclone.sql:/docker-entrypoint-initdb.d/01-leetclone.sql
    networks:
      - my-net