name: CI/CD ec2 app

on:
  push:
    branches: [develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: pull and deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          script: |
            echo "Hello from github action, start deploy main to ec2"
            cd /home/ubuntu/leetcode-clone
            docker-compose down
            docker system prune --force
            git pull origin develop 
            docker-compose build --no-cache
            docker-compose up
