name: CI/CD ec2 app

on:
  push:
    branches: [main]

jobs:
  build_express_and_socket:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy express and socket server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.HOST_DNS_MAIN }}
          username: ${{ secrets.EC2_USERNAME }}
          script: |
            cd /home/ubuntu/leetcode-clone

            # Clean up
            docker-compose -f docker-compose-main.yml down
            docker system prune -a -f
            docker volume prune -f

            # Pull change
            git fetch origin main
            git reset --hard origin/main

            # Update database
            docker run --name mysql -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -d mysql:8.0.33
            docker exec -i mysql sh -c 'exec mysql -h db-leetclone.c6iiblrlfvab.ap-northeast-3.rds.amazonaws.com -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} leetclone' < backend/dbBackup/leetclone.sql
            docker container stop mysql
            docker container rm mysql

            # Clear Redis
            docker run -it --rm redis redis-cli -h cache-leetclone.1nyq2c.ng.0001.apn3.cache.amazonaws.com -p 6379 flushall

            # Compose
            docker-compose -f docker-compose-main.yml build --no-cache
            docker-compose -f docker-compose-main.yml up -d

      - name: Deploy worker server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.HOST_DNS_WORKER }}
          username: ${{ secrets.EC2_USERNAME }}
          script: |
            cd /home/ubuntu/leetcode-clone

            #Clean up
            docker-compose -f docker-compose-worker.yml down
            docker system prune -a -f
            docker volume prune -f

            #Pull change    
            git fetch origin main
            git reset --hard origin/main

            #Compose
            docker-compose -f docker-compose-worker.yml build --no-cache
            docker-compose -f docker-compose-worker.yml up -d

      - name: Test express server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.HOST_DNS_MAIN }}
          username: ${{ secrets.EC2_USERNAME }}
          script: |
            # Test
            docker exec express_server /bin/bash -c "cd backend && npm run productionTest"
