name: CI/CD ec2 app

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: pull and deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          script: |
            cd /home/ubuntu/leetcode-clone

            #clean up
            docker-compose down
            docker system prune -a -f
            docker volume prune -f

            #pull change
            git fetch origin main
            git reset --hard origin/main

            #update db
            docker run --name mysql -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -d mysql:8.0.33
            docker exec -i mysql sh -c 'exec mysql -h db-leetclone.c6iiblrlfvab.ap-northeast-3.rds.amazonaws.com -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} leetclone' < /home/ubuntu/leetcode-clone/backend/dbBackup/leetclone.sql
            docker container stop mysql
            docker container rm mysql

            #compose
            docker-compose build --no-cache
            docker-compose up -d
