name: CI/CD counter app

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: deploy in EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          REMOTE_HOST: ${{ secrets.HOSTNAME  }}
          REMOTE_USER: ${{ secrets.USER_NAME  }}
          TARGET: "/home/ubuntu"

        run: |
          echo "Hello from github action, start deploy main to ec2"

            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/leetcode-clone
            docker-compose down
            git pull origin main 
            docker-compose up -d
          '
